name: black_box
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  tbib_splash_screen: ^1.0.0
  window_manager: ^0.3.8
  desktop_context_menu: ^0.1.1
  path: ^1.9.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.2.0
  analyzer: ^5.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sc_assault.jpg
    - assets/images/cod.jpg
    - assets/images/background.jpg
    - assets/images/vault.png
    - assets/images/tmc.png
    - assets/images/lib1-nobg-notext.png
    - assets/images/lib1-nobg.png
    - assets/images/lib2.png
    - assets/images/lib3-nobg.png
    - assets/images/lib3.png
    - assets/images/lib4.png
    - assets/images/corru_discov1.png
    - assets/images/corru_discov2.png
    - assets/images/corru_discov3.png
    - assets/images/corru_discov4.png